export const TRAINER_ACTIONS = {
  ADD_TRAINER: 'ADD_TRAINER',
  UPDATE_TRAINER: 'UPDATE_TRAINER',
  DELETE_TRAINER: 'DELETE_TRAINER',
  SET_TRAINERS: 'SET_TRAINERS',
};

export const SESSION_ACTIONS = {
  ADD_SESSION: 'ADD_SESSION',
  UPDATE_SESSION: 'UPDATE_SESSION',
  DELETE_SESSION: 'DELETE_SESSION',
  SET_SESSIONS: 'SET_SESSIONS',
};

export const ATTENDANCE_ACTIONS = {
  CHECK_IN: 'CHECK_IN',
  CHECK_OUT: 'CHECK_OUT',
  APPROVE_ATTENDANCE: 'APPROVE_ATTENDANCE',
  REJECT_ATTENDANCE: 'REJECT_ATTENDANCE',
  SET_ATTENDANCE: 'SET_ATTENDANCE',
};

export const AUTH_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};
